openapi: "3.0.1"
info:
  title: "decrypter-api"
  version: "2022-11-29 03:55:27UTC"
servers:
- url: "https://knmum7ya05.execute-api.us-west-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /password/{shaHash}:
    get:
      responses:
        default:
          description: "Default response for GET /password/{shaHash}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:654586067576:function:decrypter-lambda2/invocations"
        connectionType: "INTERNET"
    parameters:
    - name: "shaHash"
      in: "path"
      description: "Generated path parameter for shaHash"
      required: true
      schema:
        type: "string"
components:
  x-amazon-apigateway-integrations:
    unusedIntegration_lty9q13:
      payloadFormatVersion: "2.0"
      type: "aws_proxy"
      httpMethod: "POST"
      uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:654586067576:function:decrypter-function2/invocations"
      connectionType: "INTERNET"
    unusedIntegration_xyr4sgd:
      payloadFormatVersion: "2.0"
      type: "aws_proxy"
      httpMethod: "POST"
      uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:654586067576:function:decrypter-lambda/invocations"
      connectionType: "INTERNET"
    unusedIntegration_9gvhh7c:
      payloadFormatVersion: "2.0"
      type: "aws_proxy"
      httpMethod: "POST"
      uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:654586067576:function:decrypter-lambda/invocations"
      connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"
